print("Calculadora de salario quincenal")
diasMananaLV = input("Dias trabajados en la mañana de lunes a viernes: ")
diasMananaLV = float(diasMananaLV)
diasTardeLV = input("Dias trabajados en la tarde de lunes a viernes: ")
diasTardeLV = float(diasTardeLV)
diasNocLV = input("Dias trabajados en la noche de lunes a viernes: ")
diasNocLV = float(diasNocLV)
diasMananaSD = input("Dias trabajados en la mañana de sabado y domingo: ")
diasMananaSD = float(diasMananaSD)
diasTardeSD = input("Dias trabajados en la tarde de sabado y domingo: ")
diasTardeSD = float(diasTardeSD)
diasNocSD = input("Dias trabajados en la noche de sabado y domingo: ")
diasNocSD = float(diasNocSD)
salarioQuincenal = ((diasMananaLV+diasTardeLV)*150)+(diasNocLV*200)+((diasMananaSD+diasTardeSD)*(150*1.20))+(diasNocSD*(200*1.20))
print("Tú salario quincenal es:", + salarioQuincenal)